#!/usr/bin/env bash

simulator_name=$1
output_dir=$2

if [[ -z $simulator_name || -z $output_dir ]]; then
    echo "Required arguments are: simuator_name output_dir"
    exit 1
fi

mkdir -p $output_dir
while read i; do
	if [[ $i =~ Test\ Case.*\[(.*)\].*started. ]]; then
		test_name=$(echo "${BASH_REMATCH[1]}" | tr " " ".")
		test_output_path="$output_dir/$test_name"
		rm "$test_output_path.mp4" "$test_output_path.log"
		xcrun simctl io "$simulator_name" recordVideo "$test_output_path.mp4" --codec "h264" -f  &
		pid=$!
		echo "Started to record $test_name to $test_output_path"
	fi
	echo "$i"
	if [[ ! -z $test_output_path ]]; then
		echo "$i" >> "$test_output_path.log"
	fi
	if [[ $i =~ Test\ Case.*(passed|failed).* ]]; then
		kill -SIGINT $pid
		wait $pid
		echo "Finished recording at $test_output_path"
		# if [[ ${BASH_REMATCH[1]} == "passed" ]]; then
		# 	rm "$test_output_path.mp4" "$test_output_path.log"
		# fi
		test_output_path=""
	fi
done

killall simctl